"""Fused-forward schedule executor for Megatron pipeline parallelism.

Replaces Megatron's stock `forward_backward_pipelining_without_interleaving`
for the fused-forward step. Uses gloo pair groups for cross-rank P2P
(see `verl/utils/megatron/fused_p2p.py`), keeping training compute on
NCCL-resident model shards.

The schedule (per-rank op list) is generated by torch_pp's
`build_default_fused_schedule` and parsed via `parse_schedule`. Each op
is one of:
  - tF.k: training forward for micro-batch k
  - tB.k: training backward for micro-batch k
  - iF.k: inference (log-prob) forward for micro-batch k

Construction theorem (informal): for every rank r,
    max_step(iF[r,*]) < min_step(tB[r,*])
i.e. all iFs finish before that rank's first tB. This guarantees
activation memory for tF outputs isn't reclaimed until iFs are done.

Two-PP design notes
-------------------
- Training PP forward direction:    r0 → r1 → ... → r_{P-1}
- Inference PP reverse direction:   r_{P-1} → r_{P-2} → ... → r0
- iF requires a separate inference model shard with REVERSED layer
  assignment per rank. This module is currently STUB-LEVEL: the actual
  reversed-PP infer model construction is a separate task. The executor
  signature accepts `infer_model` as a parameter; the caller is
  responsible for setting it up correctly.

V1 simplification
-----------------
For initial smoke / paper bring-up, the executor supports a SIMPLER
mode (`infer_local=True`) where iF runs LOCALLY on each rank with a
full replica of the inference model. Memory-wasteful (P× model) but
no inference P2P needed. iF on rank r computes log-probs for a
micro-batch slice locally; output goes nowhere. Rank 0 (or any chosen
rank) collects log-probs from all per-rank-iF outputs.

Falls back to `infer_local=True` if `infer_model` is None.
"""
from __future__ import annotations
import logging
from contextlib import nullcontext
from typing import Any, Callable, Dict, List, Optional, Tuple

import torch
import torch.distributed as dist


logger = logging.getLogger(__name__)


class FusedScheduleExecutor:
    """Executes a fused (tF/tB/iF) schedule on Megatron PP using gloo P2P.

    Usage:
        exec = FusedScheduleExecutor(
            train_model=mcore_train_model,           # PP-sharded
            infer_model=mcore_infer_model_or_None,   # optional, reverse-PP
            forward_step_func=user_forward_step_func,
            backward_step_func=megatron_backward_step,
            data_iterator=batched_iter,
            num_microbatches=M,
            pp_size=P,
            pp_rank=r,
            pair_groups=fused_p2p_pair_groups,
            tensor_shape=(seq, mb, hidden),
            dtype=torch.bfloat16,
            device=torch.device("cuda"),
            infer_local=True,                        # v1 default
        )
        log_probs, metrics = exec.run(schedule_ops)
    """

    def __init__(
        self,
        *,
        train_model: torch.nn.Module,
        forward_step_func: Callable,
        backward_step_func: Callable,
        data_iterator,
        num_microbatches: int,
        pp_size: int,
        pp_rank: int,
        pair_groups: Dict,
        tensor_shape: Tuple[int, ...],
        dtype: torch.dtype,
        device: torch.device,
        config: Optional[Any] = None,
        infer_model: Optional[torch.nn.Module] = None,
        infer_local: bool = True,
        loss_fn_for_iF: Optional[Callable] = None,
    ):
        self.train_model = train_model
        self.infer_model = infer_model if infer_model is not None else train_model
        self.forward_step_func = forward_step_func
        self.backward_step_func = backward_step_func
        self.data_iterator = data_iterator
        self.M = num_microbatches
        self.pp_size = pp_size
        self.pp_rank = pp_rank
        self.pair_groups = pair_groups
        self.tensor_shape = tensor_shape
        self.dtype = dtype
        self.device = device
        self.config = config
        self.infer_local = infer_local
        self.loss_fn_for_iF = loss_fn_for_iF

        self.is_first = (pp_rank == 0)
        self.is_last = (pp_rank == pp_size - 1)

        # State across schedule ops
        self._tF_input: Dict[int, torch.Tensor] = {}    # mb_id → recv'd activation (with requires_grad)
        self._tF_output: Dict[int, torch.Tensor] = {}   # mb_id → forward output (saved for tB)
        self._tF_loss: Dict[int, torch.Tensor] = {}     # last stage only: loss per mb
        self._iF_logprobs: Dict[int, torch.Tensor] = {} # iF outputs (last_inf stage)
        self._pending_sends: List = []
        self._send_bufs: List = []  # keep CPU staging refs alive

    # ---- Entry point ----
    def run(self, schedule_ops):
        """Execute the schedule. `schedule_ops` is List[FusedScheduleOp]."""
        for idx, op in enumerate(schedule_ops):
            if op.op == "train_forward":
                self._do_tF(op.micro_batch_id)
            elif op.op == "train_backward":
                self._do_tB(op.micro_batch_id)
            elif op.op == "infer_forward":
                self._do_iF(op.micro_batch_id)
            else:
                raise ValueError(f"unknown op {op.op}")

        # Drain pending sends
        for h in self._pending_sends:
            h.wait()
        self._pending_sends.clear()
        self._send_bufs.clear()

        return self._iF_logprobs, {
            "n_tF": len(self._tF_output),
            "n_tB": self.M,
            "n_iF": len(self._iF_logprobs) if self.infer_local else None,
        }

    # ---- Per-op handlers ----
    def _do_tF(self, mb: int):
        from .fused_p2p import gloo_p2p_recv, gloo_p2p_send
        # 1. Recv from prev rank (if not first)
        if self.is_first:
            input_tensor = None
        else:
            input_tensor = gloo_p2p_recv(
                shape=self.tensor_shape, src_pp_rank=self.pp_rank - 1,
                dtype=self.dtype, pair_groups=self.pair_groups,
                device=self.device, dst_pp_rank=self.pp_rank,
            )
            input_tensor.requires_grad_(True)
        self._tF_input[mb] = input_tensor

        # 2. Compute via megatron forward_step
        output_tensor = self._call_megatron_forward_step(input_tensor, mb)
        self._tF_output[mb] = output_tensor

        # 3. Send to next rank (if not last)
        if not self.is_last:
            handle = gloo_p2p_send(
                output_tensor, dst_pp_rank=self.pp_rank + 1,
                pair_groups=self.pair_groups, src_pp_rank=self.pp_rank,
            )
            self._pending_sends.append(handle)
        # last stage: output_tensor is loss; backward kicks off here
        else:
            self._tF_loss[mb] = output_tensor

    def _do_tB(self, mb: int):
        from .fused_p2p import gloo_p2p_recv, gloo_p2p_send
        # 1. Recv grad from next rank (if not last)
        if self.is_last:
            output_tensor_grad = None  # last stage: loss.backward starts here
        else:
            output_tensor_grad = gloo_p2p_recv(
                shape=self.tensor_shape, src_pp_rank=self.pp_rank + 1,
                dtype=self.dtype, pair_groups=self.pair_groups,
                device=self.device, dst_pp_rank=self.pp_rank,
            )

        input_tensor = self._tF_input.get(mb)
        output_tensor = self._tF_output[mb]

        # 2. Compute backward
        input_tensor_grad = self._call_megatron_backward_step(
            input_tensor, output_tensor, output_tensor_grad,
        )

        # 3. Send grad to prev rank (if not first)
        if not self.is_first and input_tensor_grad is not None:
            handle = gloo_p2p_send(
                input_tensor_grad, dst_pp_rank=self.pp_rank - 1,
                pair_groups=self.pair_groups, src_pp_rank=self.pp_rank,
            )
            self._pending_sends.append(handle)

    def _do_iF(self, mb: int):
        """Inference forward (no grad). v1: local compute on full-replica
        infer_model. v2 (TODO): reverse-PP iF with gloo P2P."""
        if self.infer_local:
            self._do_iF_local(mb)
        else:
            self._do_iF_reverse_pp(mb)

    def _do_iF_local(self, mb: int):
        """Local-compute iF: each rank runs full-replica infer model on
        its share of the batch and stashes log-probs."""
        if self.loss_fn_for_iF is None:
            # Caller hasn't provided log-prob extraction; skip iF.
            logger.warning("iF.%d skipped: loss_fn_for_iF not provided", mb)
            return
        with torch.no_grad():
            # The caller's loss_fn_for_iF is responsible for getting the
            # micro-batch input from data_iterator and producing log-probs.
            log_probs = self.loss_fn_for_iF(
                model=self.infer_model,
                data_iterator=self.data_iterator,
                micro_batch_id=mb,
            )
        self._iF_logprobs[mb] = log_probs

    def _do_iF_reverse_pp(self, mb: int):
        """TODO: implement reverse-PP iF (mirrors torch_pp's `infer_forward`).

        Plan:
          - if not first_inf (i.e., pp_rank != P-1): recv hidden from rank+1 via gloo
          - compute infer_model.forward(input_hidden)
          - if not last_inf (i.e., pp_rank != 0): send hidden to rank-1 via gloo
          - if last_inf (pp_rank == 0): compute log_probs from final hidden
        """
        raise NotImplementedError(
            "reverse-PP iF not yet implemented; use infer_local=True "
            "(requires full-replica infer_model on each rank)"
        )

    # ---- Megatron compute hooks (thin wrappers; allow override) ----
    def _call_megatron_forward_step(self, input_tensor, mb):
        """Calls Megatron's `forward_step` with input from gloo or None
        (for first stage). Returns output_tensor (hidden for non-last,
        loss for last stage).
        """
        # Megatron's forward_step expects model to expose set_input_tensor.
        from megatron.core.utils import get_attr_wrapped_model
        set_input_tensor = get_attr_wrapped_model(self.train_model, "set_input_tensor")
        set_input_tensor([input_tensor] if input_tensor is not None else [None])

        # Call user's forward_step_func directly (bypassing megatron's
        # forward_step wrapper since we manage P2P externally).
        ctx = (torch.autocast("cuda", dtype=self.config.autocast_dtype)
               if (self.config is not None and getattr(self.config, "enable_autocast", False))
               else nullcontext())
        with ctx:
            output_tensor, loss_func = self.forward_step_func(
                self.data_iterator, self.train_model,
            )
        if self.is_last:
            # last stage: apply loss_func to compress to scalar
            if loss_func is not None:
                loss_out = loss_func(output_tensor)
                # loss_func can return tuple (loss, num_tokens, metadata) or just scalar
                if isinstance(loss_out, tuple):
                    loss = loss_out[0]
                else:
                    loss = loss_out
                # scale by num microbatches for grad accumulation
                loss = loss / self.M
                return loss
            return output_tensor
        return output_tensor

    def _call_megatron_backward_step(self, input_tensor, output_tensor, output_tensor_grad):
        """Calls Megatron's `backward_step`. Returns input_tensor_grad
        (or None if first stage)."""
        return self.backward_step_func(
            input_tensor=input_tensor,
            output_tensor=output_tensor,
            output_tensor_grad=output_tensor_grad,
            model_type=None,  # filled by caller via partial if needed
            config=self.config,
        )


def forward_backward_fused_pipelining(
    *,
    forward_step_func: Callable,
    data_iterator,
    train_model: torch.nn.Module,
    num_microbatches: int,
    pp_size: int,
    pp_rank: int,
    pair_groups: Dict,
    tensor_shape: Tuple[int, ...],
    dtype: torch.dtype,
    device: torch.device,
    config: Optional[Any] = None,
    infer_model: Optional[torch.nn.Module] = None,
    infer_local: bool = True,
    loss_fn_for_iF: Optional[Callable] = None,
    schedule_ops: Optional[list] = None,
):
    """Top-level entry; mirrors megatron's `forward_backward_pipelining_*` shape.

    If `schedule_ops` is None, fetches the default fused schedule via
    torch_pp's `build_default_fused_schedule(pp_size, num_microbatches)`.
    """
    from megatron.core.pipeline_parallel.schedules import backward_step

    if schedule_ops is None:
        from verl.workers.torch_pp.fused_schedule import (
            build_default_fused_schedule, parse_schedule,
        )
        sched = build_default_fused_schedule(pp_size, num_microbatches)
        schedule_ops = parse_schedule(sched[pp_rank])

    executor = FusedScheduleExecutor(
        train_model=train_model,
        forward_step_func=forward_step_func,
        backward_step_func=backward_step,
        data_iterator=data_iterator,
        num_microbatches=num_microbatches,
        pp_size=pp_size,
        pp_rank=pp_rank,
        pair_groups=pair_groups,
        tensor_shape=tensor_shape,
        dtype=dtype,
        device=device,
        config=config,
        infer_model=infer_model,
        infer_local=infer_local,
        loss_fn_for_iF=loss_fn_for_iF,
    )
    return executor.run(schedule_ops)
